language: node_js
install: npm install gitbook-cli
before_script:
  - sh -e ./clone.sh
script:
  - gitbook build
after_success:
  - test "$TRAVIS_BRANCH" == "master" && test -n "$GH_TOKEN" && sh -e ./deploy.sh
env:
  global:
  - GH_REF: github.com/yutannihilation/insomniac-shrimp.git
  - secure: AVLgG95zxXd/AoIGcKdISaJLs/QZH4zCfTubw9w23B8qubyF/83iBGR77t9wrKQtRJ4zSnRue7RpobY8Zr2Wd5dtsrNox9IIvBzhx7p/3QYYriIrjGMBBeXpWy62ozYAyPZhHSyFVc+mN2V7pxyhozO3PNd5G0TOWuLqDYQwHJhE66s1folE8BiueYt6WX+SJfNz9cxkLGIRSMus0FChXdpPi0hUn8yPYhhvXTtq3LN1eDgkrliscAbu/IXvHZg2mtKEbfBbwNfLvpIQxcfLQjDegbN1F6geRBFYw9KNZZdwyhnI3aneZouDtuoZyUUjKDf1eoBlispjxfsLXRmFAEdtIoZKGxgYwaatd6Kw/TVrsHhZfxReXOoaSskJzQ0l4nNOGmW84gOevxn51iMaf0l1WUmCqaIJvLoeSK3wxL6czMQoBOeW0u35AJcdrQdKQ2YcvSWw+FGqXKM03ioPNcVKWrJ4/Qo3nR+0vjCN3MKZhPWkNXIBsgmziaIlYWOOT+In2Flgy6S/T7wAa23F1WyN4+WLvBAEX4Zfo8lA3XTy82J5ysjTmXSIdSb8RXmVXUt2CtouOYoQEoB1HekHEUwyubxwIYYsMAWCyQcIVb2ur6dd2DiBnahInbYm8HjuYlFzQheMDs9Fa+wrcfX0xqNRGHfW+qaQMyVIrnK/hGU=
